plugins {
    id 'java'
    id 'maven-publish'
}

group = 'ru.clevertec'
version = '1.0'
description = 'Logger Starter'


repositories {
    mavenCentral()
}

dependencies {
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    implementation 'org.projectlombok:lombok:1.18.30'
    implementation 'org.springframework.boot:spring-boot-starter:3.4.0'
    implementation 'org.springframework.boot:spring-boot-starter-web:3.4.0'
    implementation 'org.springframework.boot:spring-boot-starter-aop:3.4.1'

    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}


jar {
    manifest {
        attributes(
                "Implementation-Title": project.name,
                "Implementation-Version": project.version
        )
    }
    archivesBaseName = project.name
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = project.group
            artifactId = project.name
            version = project.version

            from components.java
        }
    }
    repositories {
        mavenLocal()
    }
}

tasks.build {
    dependsOn publish
}